name: code-quality

on:
  push:
    branches-ignore: ['master']

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # @v2.3.4; Using hash for security purposes
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node.js 14.x
        uses: actions/setup-node@c6fd00ceb9747fb23ffdf72987450a2664414867 # @v2.1.2; Using hash for security purposes
        with:
          node-version: 14.x

      - name: Install markdownlint cli
        run: npm install markdownlint-cli

      - name: Format markdown
        run: npm run format:markdown

      - name: Commit changes
        continue-on-error: true
        run: |
          git config --global user.name '[CI] Linter'
          git config --global user.email 'siemienik@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "[CI] Linter: markdown formatted"
          git push origin
