name: xlsx-renderer

on: [push, pull_request] # todo path limitation

defaults:
  run:
    working-directory: ./packages/xlsx-renderer

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        #        node-version: [8.x, 9.x, 10.x, 11.x, 12.x, 13.x, 14.x] # version 8 and 9 isn't supported in ExcelJS as default - may I resolve it further (or ignore)
        node-version: [10.x, 11.x, 12.x, 13.x, 14.x]

    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # @v2.3.4; Using hash for security purposes
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@c6fd00ceb9747fb23ffdf72987450a2664414867 # @v2.1.2; Using hash for security purposes
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm ci
      - name: Check lint
        run: npm run lint
      - name: Check build
        run: npm run build
      - name: Check unit & integration tests with coverage
        run: npm run coverageReport
      - name: Publish coverage report
        continue-on-error: true
        run: bash <(curl -s https://codecov.io/bash) -F xlsx-renderer
        env:
          CI: true